import type { Metadata } from "next";
import { Playfair_Display, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Provider from "@/views/components/Provider";
import Header from "@/views/layout/Header";

const playfairSans = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairSans.variable} ${sourceSans.variable} antialiased`}
      >
        <Provider>
          <div className="py-6 px-[5%] sm:p-6 mx-auto min-h-screen flex flex-col gap-2">
            <Header />

            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
